py3.10 compatibility
kootenpv/cliche pull request #12
Opened 2022-05-05 22:45 UTC by ig0rsky

* https://github.com/python/cpython/commit/fb35fa49d192368e94ffec09c092260ed0fea2e1

2022-05-05 22:46 UTC, ig0rsky commented
tested with a few of the examples, seems to work fine.

2022-05-06 00:12 UTC, kootenpv commented
We definitely should maintain backwards compatibility, so I guess we should do a check for which argparse version is being used?

```
pascal@x1x:/home/pascal$ ipython
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import argparse

In [2]: argparse.__version__
Out[2]: '1.1'
```

2022-05-06 09:46 UTC, ig0rsky commented
```
ipython                                                                                                                                                                                           (mgnr-mamba-macos) 
Python 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import argparse

In [2]: argparse.__version__
Out[2]: '1.1'
```

2022-05-09 11:27 UTC, kootenpv requested changes
thanks, some small suggestions!

2022-05-09 11:27 UTC, kootenpv commented on cliche/argparser.py
> +
Just make this a constant:

```python
PYTHON_310_OR_UP = sys.version_info >= (3, 10)
```

2022-05-09 11:27 UTC, kootenpv commented on cliche/argparser.py
> +                    message = _check_py_version( message.replace("options", "OPTIONS"), message.replace("optional arguments", "OPTIONAL ARGUMENTS"))
```python
message = message.replace("options" if PYTHON_310_OR_UP else "optional arguments", "OPTIONS:")
```

2022-05-09 11:27 UTC, kootenpv commented on cliche/argparser.py
> +                            end = _check_py_version(message.index("options"), message.index("optional"))
```python
end = message.index("options " if PYTHON_310_OR_UP else "optional ")
```

2022-05-09 11:27 UTC, kootenpv commented on cliche/argparser.py
> +            option_str = _check_py_version("Unknown option", "Unknown optional argument")
```python
option_str = "Unknown option" if PYTHON_310_OR_UP else "Unknown optional argument"
```

2022-05-09 11:27 UTC, kootenpv commented on setup.py
>  VERSION = "{}.{}.{}".format(MAJOR_VERSION, MINOR_VERSION, MICRO_VERSION)
can leave it at minor=10 as from the perspective of cliche there is no significant/breaking change yet

2022-05-09 13:17 UTC, kootenpv commented
cool thanks, will test locally and upload to pypi

2022-05-09 13:17 UTC, merged